package VentanasFrame;

import Principal.AppState;
import Principal.Categoria;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class Biblioteca extends javax.swing.JFrame {

    String General = "General";

    public Biblioteca() {
        initComponents();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("BIBLIOTECA");
        String usuario = AppState.usuarioLogeado.getNombre();
        NombreLabel.setText(usuario);

        boolean saber = false;

        for (Categoria u : AppState.usuarioLogeado.categoria) {
            if (General.equals(u.getNombreCategorria())) {
                saber = true;
            }
        }
        if (saber == false) {
            Categoria cf = new Categoria(General);
            AppState.usuarioLogeado.agregarCategoria(cf);
        }

        for (Categoria ci : AppState.usuarioLogeado.categoria) {
            DefaultTableModel modeloDafault = new DefaultTableModel(new String[]{"General"}, AppState.usuarioLogeado.categoria.size());
            CategoriaTable.setModel(modeloDafault);
            TableModel modeloDatos = CategoriaTable.getModel();
            for (int i = 0; i < AppState.usuarioLogeado.categoria.size(); i++) {
                modeloDatos.setValueAt(AppState.usuarioLogeado.categoria.get(i).getNombreCategorria(), i, 0);
            }
        }

    }

    public void tablaCategoria() {

        for (Categoria ci : AppState.usuarioLogeado.categoria) {
            DefaultTableModel modeloDafault = new DefaultTableModel(new String[]{"General"}, AppState.usuarioLogeado.categoria.size());
            CategoriaTable.setModel(modeloDafault);
            TableModel modeloDatos = CategoriaTable.getModel();
            for (int i = 0; i < AppState.usuarioLogeado.categoria.size(); i++) {
                modeloDatos.setValueAt(AppState.usuarioLogeado.categoria.get(i).getNombreCategorria(), i, 0);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        AgregarFotoIButton = new javax.swing.JButton();
        EliminarIButton = new javax.swing.JButton();
        DeliteCButton = new javax.swing.JButton();
        AgregarCButton = new javax.swing.JButton();
        imagenLabel = new javax.swing.JLabel();
        AtrasButton = new javax.swing.JButton();
        AdelanteButton = new javax.swing.JButton();
        NombreLabel = new javax.swing.JLabel();
        SalirButton = new javax.swing.JButton();
        ActuralizarButton = new javax.swing.JButton();
        CategoriaTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CategoriaTable = new javax.swing.JTable();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Categorías:");

        AgregarFotoIButton.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        AgregarFotoIButton.setForeground(new java.awt.Color(0, 0, 0));
        AgregarFotoIButton.setText("Agregar Imagen");
        AgregarFotoIButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarFotoIButtonActionPerformed(evt);
            }
        });

        EliminarIButton.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        EliminarIButton.setForeground(new java.awt.Color(0, 0, 0));
        EliminarIButton.setText("Eliminar Imagen");

        DeliteCButton.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        DeliteCButton.setForeground(new java.awt.Color(0, 0, 0));
        DeliteCButton.setText("Eliminar Categoría Seleccionada");
        DeliteCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeliteCButtonActionPerformed(evt);
            }
        });

        AgregarCButton.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        AgregarCButton.setForeground(new java.awt.Color(0, 0, 0));
        AgregarCButton.setText("Agregar Categoría");
        AgregarCButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarCButtonActionPerformed(evt);
            }
        });

        imagenLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        AtrasButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AtrasButton.setText("<");
        AtrasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasButtonActionPerformed(evt);
            }
        });

        AdelanteButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AdelanteButton.setText(">");

        NombreLabel.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(0, 0, 0));
        NombreLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        SalirButton.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        SalirButton.setForeground(new java.awt.Color(0, 0, 0));
        SalirButton.setText("Salir");
        SalirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirButtonActionPerformed(evt);
            }
        });

        ActuralizarButton.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        ActuralizarButton.setForeground(new java.awt.Color(0, 0, 0));
        ActuralizarButton.setText("Mostrar Imagénes");

        CategoriaTable.setBackground(new java.awt.Color(255, 255, 255));
        CategoriaTable.setFont(new java.awt.Font("SansSerif", 0, 13)); // NOI18N
        CategoriaTable.setForeground(new java.awt.Color(0, 0, 0));
        CategoriaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Categoría"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        CategoriaTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(CategoriaTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(AgregarCButton)
                        .addGap(73, 73, 73)
                        .addComponent(ActuralizarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(DeliteCButton, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SalirButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(AtrasButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(AdelanteButton)
                            .addGap(23, 23, 23))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                            .addComponent(AgregarFotoIButton)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EliminarIButton)
                            .addGap(100, 100, 100)
                            .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(43, 43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(AgregarFotoIButton)
                            .addComponent(EliminarIButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CategoriaTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgregarCButton)
                            .addComponent(ActuralizarButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeliteCButton)
                            .addComponent(SalirButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(NombreLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(AdelanteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AtrasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AgregarFotoIButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarFotoIButtonActionPerformed
        JFileChooser selector = new JFileChooser();        
        FileNameExtensionFilter extensionFilter = new FileNameExtensionFilter("Imagenes", "jpg", "JPEG", "bmp");
        selector.setFileFilter(extensionFilter);
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = selector.getSelectedFile();
            ImageIcon imagen = new ImageIcon(archivo.getAbsolutePath());
            Image imagenRedimensionada = imagen.getImage().getScaledInstance(imagenLabel.getWidth(), imagenLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imagenRedimensionadaIcon = new ImageIcon(imagenRedimensionada);
            imagenLabel.setIcon(imagenRedimensionadaIcon);
        }

        /*
        for (File file: files) {
            try {
                ImageIcon imagen = new ImageIcon(files.getAbsolutePath());
            Image imagenRedimensionada = imagen.getImage().getScaledInstance(imagenLabel.getWidth(), imagenLabel.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon imagenRedimensionadaIcon = new ImageIcon(imagenRedimensionada);
                 
                BufferedReader lector = new BufferedReader(new FileReader(file));

                while ((linea = lector.readLine()) != null) {
                    String[] datos = linea.split(",");
                    String nombre = datos[0];
                    String contrasenia = datos[1];
                    Usuario usuario = new Usuario(nombre, contrasenia);
                    AppState.usuarios.add(usuario);
                    usuariosRegistraos += usuario.toString() + "\n";
                }
            } catch (FileNotFoundException ex) {
                Logger.getLogger(AppFrame.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(AppFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
         */
    }//GEN-LAST:event_AgregarFotoIButtonActionPerformed

    private void SalirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirButtonActionPerformed
        VentanaPrincipal ventanaPrincipal = new VentanaPrincipal();
        ventanaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_SalirButtonActionPerformed

    private void AgregarCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarCButtonActionPerformed

        String categoria = CategoriaTextField.getText();

        if (categoria.equals("")) {
            JOptionPane.showMessageDialog(null, "El campo Categoria esta Vacio!!!", "Alerta", JOptionPane.WARNING_MESSAGE);
        } else {
            for (Categoria u : AppState.usuarioLogeado.categoria) {
                if (categoria.equals(u.getNombreCategorria())) {
                    JOptionPane.showMessageDialog(this, "La Categoria ya existe!", "Alerta", JOptionPane.WARNING_MESSAGE);
                    CategoriaTextField.setText("");
                    return;
                }
            }

            Categoria cf = new Categoria(categoria);
            AppState.usuarioLogeado.agregarCategoria(cf);

            tablaCategoria();
            CategoriaTextField.setText("");
        }

    }//GEN-LAST:event_AgregarCButtonActionPerformed

    private void DeliteCButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeliteCButtonActionPerformed

        int eliminarFila = CategoriaTable.getSelectedRow();
        if (eliminarFila == 0) {
            JOptionPane.showMessageDialog(this, "La Categoria Genral NO se puede eliminar", "Alerta", JOptionPane.WARNING_MESSAGE);
        }
        if (eliminarFila >= 1) {
            AppState.usuarioLogeado.categoria.remove(eliminarFila);
            tablaCategoria();
        }
    }//GEN-LAST:event_DeliteCButtonActionPerformed

    private void AtrasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AtrasButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Biblioteca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ActuralizarButton;
    private javax.swing.JButton AdelanteButton;
    private javax.swing.JButton AgregarCButton;
    private javax.swing.JButton AgregarFotoIButton;
    private javax.swing.JButton AtrasButton;
    private javax.swing.JTable CategoriaTable;
    private javax.swing.JTextField CategoriaTextField;
    private javax.swing.JButton DeliteCButton;
    private javax.swing.JButton EliminarIButton;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JButton SalirButton;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
